services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: investments
    ports:
      - "9920:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
# Comment out when running service locally
#  api:
#    container_name: isa-investment-funds
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#      - "8082:8082"
#    tty: true
#    restart: on-failure
#    depends_on:
#      - postgres
#    environment:
#      NAMESPACE: docker
#      CGO_ENABLED: 0

volumes:
  postgres_data: {}
