name: Go Setup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: 1.56.2
          skip-build-cache: true
          skip-pkg-cache: true
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...